#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Thu Sep 20 16:42:50 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

import os.path
from cockpit.util.files import ROOT_DIR
from cockpit import depot
from cockpit import events

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((393, 340))
        self.panel_26 = wx.Panel(self, wx.ID_ANY)
        self.panel_1 = wx.Panel(self.panel_26, wx.ID_ANY)
        self.north_arrow = wx.BitmapButton(self.panel_26, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/north_arrow.png", wx.BITMAP_TYPE_ANY))
        self.panel_2 = wx.Panel(self.panel_26, wx.ID_ANY)
        self.west_arrow = wx.BitmapButton(self.panel_26, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/west_arrow.png", wx.BITMAP_TYPE_ANY))
        self.centreStage = wx.BitmapButton(self.panel_26, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/centre.png", wx.BITMAP_TYPE_ANY))
        self.east_arrow = wx.BitmapButton(self.panel_26, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/east_arrow.png", wx.BITMAP_TYPE_ANY))
        self.panel_3 = wx.Panel(self.panel_26, wx.ID_ANY)
        self.south_arrow = wx.BitmapButton(self.panel_26, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/south_arrow.png", wx.BITMAP_TYPE_ANY))
        self.panel_4 = wx.Panel(self.panel_26, wx.ID_ANY)
        self.panel_31 = wx.Panel(self.panel_26, wx.ID_ANY, style=wx.BORDER_SUNKEN)
        self.up_arrow = wx.BitmapButton(self.panel_26, wx.ID_ANY, wx.Bitmap(ROOT_DIR+ROOT_DIR+"/icons/icon_pngs_small/up_arrow.png", wx.BITMAP_TYPE_ANY))
        self.down_arrow = wx.BitmapButton(self.panel_26, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/down_arrow.png", wx.BITMAP_TYPE_ANY))
        self.panel_27 = wx.Panel(self, wx.ID_ANY)
        self.panel_28 = wx.Panel(self.panel_27, wx.ID_ANY, style=wx.BORDER_SUNKEN)
        self.bitmap_button_1 = wx.BitmapButton(self.panel_28, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/z_bot_set.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_2 = wx.BitmapButton(self.panel_28, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pn`gs_small/z_mid_set.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_3 = wx.BitmapButton(self.panel_28, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/z_top_set.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_4 = wx.BitmapButton(self.panel_28, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/point_set.png", wx.BITMAP_TYPE_ANY))
        self.panel_29 = wx.Panel(self.panel_27, wx.ID_ANY, style=wx.BORDER_RAISED)
        self.bitmap_button_13 = wx.BitmapButton(self.panel_29, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/photo.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_6 = wx.BitmapButton(self.panel_29, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/video.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_7 = wx.BitmapButton(self.panel_29, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/pause.png", wx.BITMAP_TYPE_ANY))
        self.button_1 = wx.Button(self.panel_29, wx.ID_ANY, "ABORT", style=wx.BORDER_NONE | wx.BU_EXACTFIT)
        self.panel_30 = wx.Panel(self.panel_27, wx.ID_ANY, style=wx.BORDER_RAISED)
        self.bitmap_button_9 = wx.BitmapButton(self.panel_30, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/z_bot_visit.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_10 = wx.BitmapButton(self.panel_30, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/z_mid_visit.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_11 = wx.BitmapButton(self.panel_30, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/z_top_visit.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_12 = wx.BitmapButton(self.panel_30, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/point_visit.png", wx.BITMAP_TYPE_ANY))
        self.button_13 = wx.Button(self, wx.ID_ANY, "BLANK1")
        self.button_14 = wx.Button(self, wx.ID_ANY, "BLANK2")
        self.button_15 = wx.Button(self, wx.ID_ANY, "BLANK3")
        self.button_16 = wx.Button(self, wx.ID_ANY, "BLANK4")
        self.button_17 = wx.Button(self, wx.ID_ANY, "BLANK5")
        self.button_18 = wx.Button(self, wx.ID_ANY, "BLANK6")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Controls")
        self.SetBackgroundColour(wx.Colour(207, 207, 207))
        self.north_arrow.SetSize(self.north_arrow.GetBestSize())
        self.west_arrow.SetSize(self.west_arrow.GetBestSize())
        self.centreStage.SetSize(self.centreStage.GetBestSize())
        self.east_arrow.SetSize(self.east_arrow.GetBestSize())
        self.south_arrow.SetSize(self.south_arrow.GetBestSize())
        self.panel_31.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.up_arrow.SetSize(self.up_arrow.GetBestSize())
        self.down_arrow.SetSize(self.down_arrow.GetBestSize())
        self.panel_26.SetBackgroundColour(wx.Colour(207, 207, 207))
        self.bitmap_button_1.SetSize(self.bitmap_button_1.GetBestSize())
        self.bitmap_button_2.SetSize(self.bitmap_button_2.GetBestSize())
        self.bitmap_button_3.SetSize(self.bitmap_button_3.GetBestSize())
        self.bitmap_button_4.SetSize(self.bitmap_button_4.GetBestSize())
        self.bitmap_button_13.SetSize(self.bitmap_button_13.GetBestSize())
        self.bitmap_button_6.SetSize(self.bitmap_button_6.GetBestSize())
        self.bitmap_button_7.SetSize(self.bitmap_button_7.GetBestSize())
        self.button_1.SetBackgroundColour(wx.Colour(255, 5, 155))
        self.button_1.SetForegroundColour(wx.Colour(255, 5, 155))
        self.button_1.SetFont(wx.Font(24, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.bitmap_button_9.SetSize(self.bitmap_button_9.GetBestSize())
        self.bitmap_button_10.SetSize(self.bitmap_button_10.GetBestSize())
        self.bitmap_button_11.SetSize(self.bitmap_button_11.GetBestSize())
        self.bitmap_button_12.SetSize(self.bitmap_button_12.GetBestSize())
        self.button_13.Enable(False)
        self.button_14.Enable(False)
        self.button_15.Enable(False)
        self.button_16.Enable(False)
        self.button_17.Enable(False)
        self.button_18.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_39 = wx.BoxSizer(wx.VERTICAL)
        sizer_40 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(0, 3, 0, 0)
        sizer_41 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_43 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_44 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.GridSizer(0, 3, 0, 0)
        grid_sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.north_arrow, 0, 0, 0)
        grid_sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.west_arrow, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_2.Add(self.centreStage, 0, 0, 0)
        grid_sizer_2.Add(self.east_arrow, 0, 0, 0)
        grid_sizer_2.Add(self.panel_3, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.south_arrow, 0, 0, 0)
        grid_sizer_2.Add(self.panel_4, 1, wx.EXPAND, 0)
        sizer_43.Add(grid_sizer_2, 3, wx.ALIGN_CENTER | wx.LEFT | wx.TOP, 10)
        label_16 = wx.StaticText(self.panel_31, wx.ID_ANY, "X:746.00  Y:8905.45  \nZ:654.79\n\nLens: 20X 0.75\n\nFrame size: 512 x 512\nPixel Size: 0.098 : 0.098 : 0.20", style=wx.ALIGN_LEFT)
        sizer_44.Add(label_16, 0, wx.EXPAND, 0)
        self.panel_31.SetSizer(sizer_44)
        sizer_43.Add(self.panel_31, 5, wx.ALL | wx.EXPAND, 10)
        sizer_8.Add(self.up_arrow, 0, wx.ALIGN_RIGHT, 0)
        sizer_8.Add(self.down_arrow, 0, wx.ALIGN_RIGHT, 0)
        sizer_43.Add(sizer_8, 1, wx.ALIGN_CENTER | wx.RIGHT | wx.SHAPED, 10)
        self.panel_26.SetSizer(sizer_43)
        sizer_40.Add(self.panel_26, 3, wx.EXPAND, 0)
        sizer_9.Add(self.bitmap_button_1, 0, 0, 0)
        sizer_9.Add(self.bitmap_button_2, 0, 0, 0)
        sizer_9.Add(self.bitmap_button_3, 0, 0, 0)
        sizer_5.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_5.Add(self.bitmap_button_4, 0, wx.EXPAND, 0)
        self.panel_28.SetSizer(sizer_5)
        sizer_41.Add(self.panel_28, 1, wx.EXPAND, 0)
        sizer_10.Add(self.bitmap_button_13, 0, 0, 0)
        sizer_10.Add(self.bitmap_button_6, 0, 0, 0)
        sizer_10.Add(self.bitmap_button_7, 0, 0, 0)
        sizer_6.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_6.Add(self.button_1, 0, wx.ALL | wx.EXPAND | wx.SHAPED, 3)
        self.panel_29.SetSizer(sizer_6)
        sizer_41.Add(self.panel_29, 1, wx.EXPAND, 0)
        sizer_12.Add(self.bitmap_button_9, 0, 0, 0)
        sizer_12.Add(self.bitmap_button_10, 0, 0, 0)
        sizer_12.Add(self.bitmap_button_11, 0, 0, 0)
        sizer_11.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_11.Add(self.bitmap_button_12, 0, wx.EXPAND, 0)
        self.panel_30.SetSizer(sizer_11)
        sizer_41.Add(self.panel_30, 1, wx.EXPAND, 0)
        self.panel_27.SetSizer(sizer_41)
        sizer_40.Add(self.panel_27, 2, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 10)
        grid_sizer_1.Add(self.button_13, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 3)
        grid_sizer_1.Add(self.button_14, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 3)
        grid_sizer_1.Add(self.button_15, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 3)
        grid_sizer_1.Add(self.button_16, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 3)
        grid_sizer_1.Add(self.button_17, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 3)
        grid_sizer_1.Add(self.button_18, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 3)
        sizer_40.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 5)
        sizer_39.Add(sizer_40, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_39)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class MyFrame

class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.FRAME_FLOAT_ON_PARENT | wx.RESIZE_BORDER
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((746, 340))
        self.panel_6 = wx.Panel(self, wx.ID_ANY)
        self.bitmap_button_7 = wx.BitmapButton(self.panel_6, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/path_configure.png", wx.BITMAP_TYPE_ANY))
        self.combo_box_1 = wx.ComboBox(self.panel_6, wx.ID_ANY, choices=["Live Drawer", "GFP - RFP", "Quad"], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)

        #get objective list
        self.objectives = depot.getHandlersOfType(depot.OBJECTIVE)[0]
        self.objectiveList = self.objectives.sortedObjectives
        self.pixelSize=self.objectives.getPixelSize()
        #populate dropdown.
        self.combo_box_obj = wx.ComboBox(self.panel_6, wx.ID_ANY,
                                       choices=self.objectiveList,
                                       style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.Bind(wx.EVT_COMBOBOX, self.changeObjective, self.combo_box_obj)
        
        self.panel_12 = wx.Panel(self.panel_6, wx.ID_ANY)
        self.combo_box_19 = wx.ComboBox(self.panel_6, wx.ID_ANY, choices=["512 x 512", "256 x 256", "128 x 128", "Custom.."], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.panel_8 = wx.Panel(self, wx.ID_ANY, style=wx.BORDER_SUNKEN)
        self.button_3 = wx.ToggleButton(self.panel_8, wx.ID_ANY, "On/Off")
        self.button_4 = wx.Button(self.panel_8, wx.ID_ANY, "Configure")
        self.combo_box_4 = wx.ComboBox(self.panel_8, wx.ID_ANY, choices=["DAPI : 405", "GFP : 488", "RFP : 594", "CY5 : 640"], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.combo_box_3 = wx.ComboBox(self.panel_8, wx.ID_ANY, choices=["100%", "90%", "80%", "70%", "60%", "50%", "40%", "30%", "20%", "10%"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_4 = wx.Slider(self.panel_8, wx.ID_ANY, 3, 0, 10)
        self.combo_box_5 = wx.ComboBox(self.panel_8, wx.ID_ANY, choices=["100%", "90%", "80%", "70%", "60%", "50%", "40%", "30%", "20%", "10%"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_5 = wx.Slider(self.panel_8, wx.ID_ANY, 0, 0, 10)
        self.combo_box_6 = wx.ComboBox(self.panel_8, wx.ID_ANY, choices=["0.01", "0.02", "0.03", "0.04", "0.05", "0.06", "0.07", "0.08", "0.09", "0.1"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_6 = wx.Slider(self.panel_8, wx.ID_ANY, 0, 0, 10)
        self.panel_15 = wx.Panel(self, wx.ID_ANY, style=wx.BORDER_SUNKEN)
        self.button_5 = wx.ToggleButton(self.panel_15, wx.ID_ANY, "On/Off")
        self.button_6 = wx.Button(self.panel_15, wx.ID_ANY, "Configure")
        self.combo_box_7 = wx.ComboBox(self.panel_15, wx.ID_ANY, choices=["DAPI : 405", "GFP : 488", "RFP : 594", "CY5 : 640"], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.combo_box_8 = wx.ComboBox(self.panel_15, wx.ID_ANY, choices=["100%", "90%", "80%", "70%", "60%", "50%", "40%", "30%", "20%", "10%"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_7 = wx.Slider(self.panel_15, wx.ID_ANY, 5, 0, 10)
        self.combo_box_9 = wx.ComboBox(self.panel_15, wx.ID_ANY, choices=["100%", "90%", "80%", "70%", "60%", "50%", "40%", "30%", "20%", "10%"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_8 = wx.Slider(self.panel_15, wx.ID_ANY, 0, 0, 10)
        self.combo_box_10 = wx.ComboBox(self.panel_15, wx.ID_ANY, choices=["0.01", "0.02", "0.03", "0.04", "0.05", "0.06", "0.07", "0.08", "0.09", "0.1"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_9 = wx.Slider(self.panel_15, wx.ID_ANY, 0, 0, 10)
        self.panel_14 = wx.Panel(self, wx.ID_ANY, style=wx.BORDER_SUNKEN)
        self.button_7 = wx.ToggleButton(self.panel_14, wx.ID_ANY, "On/Off")
        self.button_8 = wx.Button(self.panel_14, wx.ID_ANY, "Configure")
        self.combo_box_11 = wx.ComboBox(self.panel_14, wx.ID_ANY, choices=["DAPI : 405", "GFP : 488", "RFP : 594", "CY5 : 640"], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.combo_box_12 = wx.ComboBox(self.panel_14, wx.ID_ANY, choices=["100%", "90%", "80%", "70%", "60%", "50%", "40%", "30%", "20%", "10%"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_10 = wx.Slider(self.panel_14, wx.ID_ANY, 1, 0, 10)
        self.combo_box_13 = wx.ComboBox(self.panel_14, wx.ID_ANY, choices=["100%", "90%", "80%", "70%", "60%", "50%", "40%", "30%", "20%", "10%"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_11 = wx.Slider(self.panel_14, wx.ID_ANY, 0, 0, 10)
        self.combo_box_14 = wx.ComboBox(self.panel_14, wx.ID_ANY, choices=["0.01", "0.02", "0.03", "0.04", "0.05", "0.06", "0.07", "0.08", "0.09", "0.1"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_12 = wx.Slider(self.panel_14, wx.ID_ANY, 0, 0, 10)
        self.panel_11 = wx.Panel(self, wx.ID_ANY, style=wx.BORDER_SUNKEN)
        self.button_10 = wx.ToggleButton(self.panel_11, wx.ID_ANY, "On/Off")
        self.button_11 = wx.Button(self.panel_11, wx.ID_ANY, "Configure")
        self.combo_box_15 = wx.ComboBox(self.panel_11, wx.ID_ANY, choices=["DAPI : 405", "GFP : 488", "RFP : 594", "CY5 : 640"], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.combo_box_16 = wx.ComboBox(self.panel_11, wx.ID_ANY, choices=["100%", "90%", "80%", "70%", "60%", "50%", "40%", "30%", "20%", "10%"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_13 = wx.Slider(self.panel_11, wx.ID_ANY, 10, 0, 10)
        self.combo_box_17 = wx.ComboBox(self.panel_11, wx.ID_ANY, choices=["100%", "90%", "80%", "70%", "60%", "50%", "40%", "30%", "20%", "10%"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_14 = wx.Slider(self.panel_11, wx.ID_ANY, 0, 0, 10)
        self.combo_box_18 = wx.ComboBox(self.panel_11, wx.ID_ANY, choices=["0.01", "0.02", "0.03", "0.04", "0.05", "0.06", "0.07", "0.08", "0.09", "0.1"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.slider_15 = wx.Slider(self.panel_11, wx.ID_ANY, 0, 0, 10)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade


        events.subscribe('objective change', self.onObjectiveChange)

    def onObjectiveChange(self, name, pixelSize, transform, offset, **kwargs):
        self.combo_box_obj.SetValue(name)
        self.pixelSize=pixelSize
        self.pixelSize_label.SetLabel( "Pixel size: "+str(self.pixelSize)+":"+str(self.pixelSize)+" um\t\tFrame size:")
        
    def changeObjective(self,newValue):
        newObj=self.combo_box_obj.GetValue()
        self.objectives.changeObjective(newObj)
        self.PixelSize=self.objectives.getPixelSize()
        
    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle("Paths")
        self.bitmap_button_7.SetSize(self.bitmap_button_7.GetBestSize())
        self.combo_box_4.SetSelection(0)
        self.combo_box_3.SetMinSize((60, 26))
        self.combo_box_3.SetSelection(0)
        self.combo_box_5.SetMinSize((60, 26))
        self.combo_box_5.SetSelection(0)
        self.combo_box_6.SetMinSize((60, 26))
        self.combo_box_6.SetSelection(0)
        self.panel_8.SetBackgroundColour(wx.Colour(207, 207, 207))
        self.combo_box_7.SetSelection(0)
        self.combo_box_8.SetMinSize((60, 26))
        self.combo_box_8.SetSelection(0)
        self.combo_box_9.SetMinSize((60, 26))
        self.combo_box_9.SetSelection(0)
        self.combo_box_10.SetMinSize((60, 26))
        self.combo_box_10.SetSelection(0)
        self.combo_box_11.SetSelection(0)
        self.combo_box_12.SetMinSize((60, 26))
        self.combo_box_12.SetSelection(0)
        self.combo_box_13.SetMinSize((60, 26))
        self.combo_box_13.SetSelection(0)
        self.combo_box_14.SetMinSize((60, 26))
        self.combo_box_14.SetSelection(0)
        self.panel_14.SetBackgroundColour(wx.Colour(207, 207, 207))
        self.combo_box_15.SetSelection(0)
        self.combo_box_16.SetMinSize((60, 26))
        self.combo_box_16.SetSelection(0)
        self.combo_box_17.SetMinSize((60, 26))
        self.combo_box_17.SetSelection(0)
        self.combo_box_18.SetMinSize((60, 26))
        self.combo_box_18.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_25 = wx.BoxSizer(wx.VERTICAL)
        sizer_27 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_26 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_22 = wx.BoxSizer(wx.VERTICAL)
        sizer_24 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_21 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16 = wx.BoxSizer(wx.VERTICAL)
        sizer_19 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7.Add(self.bitmap_button_7, 0, wx.ALL, 5)
        sizer_7.Add(self.combo_box_1, 2, wx.ALIGN_CENTER | wx.ALL, 6)
        sizer_7.Add(self.combo_box_obj, 2, wx.ALIGN_CENTER | wx.ALL, 6)
        sizer_7.Add(self.panel_12, 2, wx.EXPAND, 0)
        self.pixelSize_label = wx.StaticText(self.panel_6, wx.ID_ANY, "Pixel size: "+str(self.pixelSize)+":"+str(self.pixelSize)+" um\t\tFrame size:", style=wx.ALIGN_CENTER)
        sizer_7.Add(self.pixelSize_label, 2, wx.ALIGN_CENTER, 0)
        sizer_7.Add(self.combo_box_19, 2, wx.ALIGN_CENTER | wx.ALL, 6)
        self.panel_6.SetSizer(sizer_7)
        sizer_3.Add(self.panel_6, 1, wx.EXPAND, 0)
        sizer_18.Add(self.button_3, 0, 0, 0)
        sizer_18.Add(self.button_4, 0, 0, 0)
        sizer_16.Add(sizer_18, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        sizer_19.Add(self.combo_box_4, 0, wx.ALIGN_CENTER | wx.BOTTOM, 15)
        label_1 = wx.StaticText(self.panel_8, wx.ID_ANY, "Power: ")
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(self.combo_box_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_19.Add(sizer_1, 1, wx.ALIGN_CENTER, 0)
        sizer_19.Add(self.slider_4, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        label_2 = wx.StaticText(self.panel_8, wx.ID_ANY, "ND:", style=wx.ALIGN_CENTER)
        sizer_2.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.combo_box_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_19.Add(sizer_2, 1, wx.ALIGN_CENTER, 0)
        sizer_19.Add(self.slider_5, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        label_3 = wx.StaticText(self.panel_8, wx.ID_ANY, "Exposure:")
        sizer_5.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.combo_box_6, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_19.Add(sizer_5, 1, wx.ALIGN_CENTER, 0)
        sizer_19.Add(self.slider_6, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        sizer_16.Add(sizer_19, 1, wx.EXPAND, 0)
        self.panel_8.SetSizer(sizer_16)
        sizer_4.Add(self.panel_8, 1, wx.ALL | wx.EXPAND, 5)
        sizer_20.Add(self.button_5, 0, 0, 0)
        sizer_20.Add(self.button_6, 0, 0, 0)
        sizer_17.Add(sizer_20, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        sizer_21.Add(self.combo_box_7, 0, wx.ALIGN_CENTER | wx.BOTTOM, 15)
        label_4 = wx.StaticText(self.panel_15, wx.ID_ANY, "Power: ")
        sizer_6.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.combo_box_8, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_21.Add(sizer_6, 1, wx.ALIGN_CENTER, 0)
        sizer_21.Add(self.slider_7, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        label_5 = wx.StaticText(self.panel_15, wx.ID_ANY, "ND:", style=wx.ALIGN_CENTER)
        sizer_8.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_8.Add(self.combo_box_9, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_21.Add(sizer_8, 1, wx.ALIGN_CENTER, 0)
        sizer_21.Add(self.slider_8, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        label_6 = wx.StaticText(self.panel_15, wx.ID_ANY, "Exposure:")
        sizer_9.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_9.Add(self.combo_box_10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_21.Add(sizer_9, 1, wx.ALIGN_CENTER, 0)
        sizer_21.Add(self.slider_9, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        sizer_17.Add(sizer_21, 1, wx.EXPAND, 0)
        self.panel_15.SetSizer(sizer_17)
        sizer_4.Add(self.panel_15, 1, wx.ALL | wx.EXPAND, 5)
        sizer_23.Add(self.button_7, 0, 0, 0)
        sizer_23.Add(self.button_8, 0, 0, 0)
        sizer_22.Add(sizer_23, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        sizer_24.Add(self.combo_box_11, 0, wx.ALIGN_CENTER | wx.BOTTOM, 15)
        label_7 = wx.StaticText(self.panel_14, wx.ID_ANY, "Power: ")
        sizer_10.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_10.Add(self.combo_box_12, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_24.Add(sizer_10, 1, wx.ALIGN_CENTER, 0)
        sizer_24.Add(self.slider_10, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        label_8 = wx.StaticText(self.panel_14, wx.ID_ANY, "ND:", style=wx.ALIGN_CENTER)
        sizer_11.Add(label_8, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_11.Add(self.combo_box_13, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_24.Add(sizer_11, 1, wx.ALIGN_CENTER, 0)
        sizer_24.Add(self.slider_11, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        label_9 = wx.StaticText(self.panel_14, wx.ID_ANY, "Exposure:")
        sizer_12.Add(label_9, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_12.Add(self.combo_box_14, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_24.Add(sizer_12, 1, wx.ALIGN_CENTER, 0)
        sizer_24.Add(self.slider_12, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        sizer_22.Add(sizer_24, 1, wx.EXPAND, 0)
        self.panel_14.SetSizer(sizer_22)
        sizer_4.Add(self.panel_14, 1, wx.ALL | wx.EXPAND, 5)
        sizer_26.Add(self.button_10, 0, 0, 0)
        sizer_26.Add(self.button_11, 0, 0, 0)
        sizer_25.Add(sizer_26, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        sizer_27.Add(self.combo_box_15, 0, wx.ALIGN_CENTER | wx.BOTTOM, 15)
        label_10 = wx.StaticText(self.panel_11, wx.ID_ANY, "Power: ")
        sizer_13.Add(label_10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_13.Add(self.combo_box_16, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_27.Add(sizer_13, 1, wx.ALIGN_CENTER, 0)
        sizer_27.Add(self.slider_13, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        label_11 = wx.StaticText(self.panel_11, wx.ID_ANY, "ND:", style=wx.ALIGN_CENTER)
        sizer_14.Add(label_11, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_14.Add(self.combo_box_17, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_27.Add(sizer_14, 1, wx.ALIGN_CENTER, 0)
        sizer_27.Add(self.slider_14, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        label_12 = wx.StaticText(self.panel_11, wx.ID_ANY, "Exposure:")
        sizer_15.Add(label_12, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_15.Add(self.combo_box_18, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_27.Add(sizer_15, 1, wx.ALIGN_CENTER, 0)
        sizer_27.Add(self.slider_15, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 15)
        sizer_25.Add(sizer_27, 1, wx.EXPAND, 0)
        self.panel_11.SetSizer(sizer_25)
        sizer_4.Add(self.panel_11, 1, wx.ALL | wx.EXPAND, 5)
        sizer_3.Add(sizer_4, 7, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class MyFrame1

class MyFrame2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((746, 340))
        self.panel_6 = wx.Panel(self, wx.ID_ANY, style=wx.BORDER_SUNKEN)
        self.bitmap_button_15 = wx.BitmapButton(self.panel_6, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/path_recycle.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_18 = wx.BitmapButton(self.panel_6, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/path_configure.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_14 = wx.BitmapButton(self.panel_6, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/experiment.png", wx.BITMAP_TYPE_ANY))
        self.panel_34 = wx.Panel(self.panel_6, wx.ID_ANY)
        self.text_ctrl_2 = wx.TextCtrl(self.panel_6, wx.ID_ANY, "Exp. file:", style=wx.TE_NOHIDESEL)
        self.button_11 = wx.Button(self.panel_6, wx.ID_ANY, u"\u2026")
        self.bitmap_button_16 = wx.BitmapButton(self.panel_6, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/upload.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_17 = wx.BitmapButton(self.panel_6, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/download.png", wx.BITMAP_TYPE_ANY))
        self.panel_33 = wx.Panel(self.panel_6, wx.ID_ANY)
        self.text_ctrl_3 = wx.TextCtrl(self.panel_6, wx.ID_ANY, "Image file:")
        self.button_12 = wx.Button(self.panel_6, wx.ID_ANY, u"\u2026")
        self.panel_35 = wx.Panel(self.panel_6, wx.ID_ANY)
        self.bitmap_button_12 = wx.BitmapButton(self.panel_6, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/play.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_11 = wx.BitmapButton(self.panel_6, wx.ID_ANY, wx.Bitmap(ROOT_DIR+"/icons/icon_pngs_small/stop.png", wx.BITMAP_TYPE_ANY))
        self.panel_15 = wx.Panel(self, wx.ID_ANY, style=wx.BORDER_SUNKEN)
        self.checkbox_2 = wx.CheckBox(self.panel_15, wx.ID_ANY, "Points:")
        self.button_10 = wx.ToggleButton(self.panel_15, wx.ID_ANY, "Select/clear all")
        self.check_list_box_1 = wx.CheckListBox(self.panel_15, wx.ID_ANY, choices=["X: 9098.00 Y: 7579.00", "X: 9098.00 Y: 7579.00", "X: 9098.00 Y: 7579.00", "X: 9098.00 Y: 7579.00", "X: 9098.00 Y: 7579.00", "X: 9098.00 Y: 7579.00", "X: 9098.00 Y: 7579.00", "X: 9098.00 Y: 7579.00", "X: 9098.00 Y: 7579.00", "X: 9098.00 Y: 7579.00", "X: 9098.00 Y: 7579.00"], style=wx.LB_HSCROLL)
        self.text_ctrl_1 = wx.TextCtrl(self.panel_15, wx.ID_ANY, "10")
        self.panel_32 = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.BORDER_SUNKEN)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame2.__set_properties
        self.SetTitle("Experiment")
        self.bitmap_button_15.SetSize(self.bitmap_button_15.GetBestSize())
        self.bitmap_button_18.SetSize(self.bitmap_button_18.GetBestSize())
        self.bitmap_button_14.SetSize(self.bitmap_button_14.GetBestSize())
        self.button_11.SetMinSize((30, 21))
        self.bitmap_button_16.SetSize(self.bitmap_button_16.GetBestSize())
        self.bitmap_button_17.SetSize(self.bitmap_button_17.GetBestSize())
        self.button_12.SetMinSize((30, 21))
        self.bitmap_button_12.SetSize(self.bitmap_button_12.GetBestSize())
        self.bitmap_button_11.SetSize(self.bitmap_button_11.GetBestSize())
        self.panel_32.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.panel_32.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame2.__do_layout
        sizer_26 = wx.BoxSizer(wx.VERTICAL)
        sizer_27 = wx.BoxSizer(wx.VERTICAL)
        sizer_28 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_48 = wx.BoxSizer(wx.VERTICAL)
        sizer_29 = wx.BoxSizer(wx.VERTICAL)
        sizer_32 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_31 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_45 = wx.BoxSizer(wx.VERTICAL)
        sizer_46 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_47 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7.Add(self.bitmap_button_15, 0, 0, 0)
        sizer_7.Add(self.bitmap_button_18, 0, 0, 0)
        sizer_7.Add(self.bitmap_button_14, 0, 0, 0)
        sizer_7.Add(self.panel_34, 1, wx.EXPAND, 0)
        sizer_7.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER, 0)
        sizer_7.Add(self.button_11, 0, wx.ALIGN_CENTER | wx.SHAPED, 0)
        sizer_7.Add(self.bitmap_button_16, 0, 0, 0)
        sizer_7.Add(self.bitmap_button_17, 0, 0, 0)
        sizer_7.Add(self.panel_33, 1, wx.EXPAND, 0)
        sizer_7.Add(self.text_ctrl_3, 0, wx.ALIGN_CENTER, 0)
        sizer_7.Add(self.button_12, 0, wx.ALIGN_CENTER | wx.SHAPED, 0)
        sizer_7.Add(self.panel_35, 1, wx.EXPAND, 0)
        sizer_7.Add(self.bitmap_button_12, 0, 0, 0)
        sizer_7.Add(self.bitmap_button_11, 0, 0, 0)
        self.panel_6.SetSizer(sizer_7)
        sizer_26.Add(self.panel_6, 1, wx.ALL | wx.EXPAND, 0)
        sizer_47.Add(self.checkbox_2, 0, wx.ALIGN_CENTER, 0)
        sizer_47.Add(self.button_10, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.LEFT, 30)
        sizer_46.Add(sizer_47, 1, wx.EXPAND, 0)
        sizer_45.Add(sizer_46, 1, wx.EXPAND, 0)
        sizer_31.Add(sizer_45, 1, wx.EXPAND, 0)
        sizer_29.Add(sizer_31, 1, wx.EXPAND, 0)
        sizer_29.Add(self.check_list_box_1, 6, wx.EXPAND, 0)
        sizer_32.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER | wx.LEFT | wx.SHAPED, 27)
        label_14 = wx.StaticText(self.panel_15, wx.ID_ANY, "Cycles")
        sizer_32.Add(label_14, 1, wx.ALIGN_CENTER, 0)
        sizer_29.Add(sizer_32, 1, wx.ALIGN_CENTER | wx.EXPAND, 0)
        self.panel_15.SetSizer(sizer_29)
        sizer_28.Add(self.panel_15, 0, wx.ALL | wx.EXPAND | wx.SHAPED, 10)
        label_17 = wx.StaticText(self.panel_32, wx.ID_ANY, "this box will contain\na detailed and clear\ndescription of all parameters of the experiment\n\n\nthis box will contain\na detailed and clear\ndescription of all parameters of the experiment\n\n\n\nthis box will contain\na detailed and clear\ndescription of all parameters of the experiment\n\n\n\nthis box will contain\na detailed and clear\ndescription of all parameters of the experiment")
        sizer_48.Add(label_17, 0, wx.ALL, 4)
        self.panel_32.SetSizer(sizer_48)
        sizer_28.Add(self.panel_32, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 10)
        sizer_27.Add(sizer_28, 1, wx.EXPAND, 0)
        sizer_26.Add(sizer_27, 7, wx.EXPAND, 0)
        self.SetSizer(sizer_26)
        self.Layout()
        # end wxGlade

# end of class MyFrame2

class MyFrame3(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame3.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((700, 350))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame3.__set_properties
        self.SetTitle("Stage Viewer")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame3.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("screenshots/Screen Shot 2018-09-12 at 12.05.56.png", wx.BITMAP_TYPE_ANY), style=wx.FULL_REPAINT_ON_RESIZE)
        sizer_2.Add(bitmap_1, 0, wx.ALIGN_CENTER, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

# end of class MyFrame3

class MyFrame4(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame4.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((700, 445))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame4.__set_properties
        self.SetTitle("Mosaic")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame4.__do_layout
        sizer_35 = wx.BoxSizer(wx.VERTICAL)
        bitmap_2 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("screenshots/Screen Shot 2018-09-12 at 12.05.35.png", wx.BITMAP_TYPE_ANY))
        bitmap_2.SetMinSize((800, 407))
        sizer_35.Add(bitmap_2, 0, wx.ALIGN_CENTER, 0)
        self.SetSizer(sizer_35)
        self.Layout()
        # end wxGlade

# end of class MyFrame4

class MyFrame5(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame5.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1210, 795))
        self.panel_19 = wx.Panel(self, wx.ID_ANY)
        self.panel_18 = wx.Panel(self, wx.ID_ANY)
        self.panel_21 = wx.Panel(self, wx.ID_ANY)
        self.panel_20 = wx.Panel(self, wx.ID_ANY)
        self.panel_22 = wx.Panel(self, wx.ID_ANY)
        self.panel_23 = wx.Panel(self, wx.ID_ANY)
        self.panel_24 = wx.Panel(self, wx.ID_ANY)
        self.panel_25 = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame5.__set_properties
        self.SetTitle("Image Window")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame5.__do_layout
        sizer_36 = wx.BoxSizer(wx.VERTICAL)
        sizer_37 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_3 = wx.GridSizer(0, 3, 0, 0)
        sizer_38 = wx.BoxSizer(wx.VERTICAL)
        bitmap_4 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("logos/image_example.jpg", wx.BITMAP_TYPE_ANY), style=wx.BORDER_SUNKEN)
        sizer_38.Add(bitmap_4, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        bitmap_5 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("logos/image_example.jpg", wx.BITMAP_TYPE_ANY), style=wx.BORDER_SUNKEN)
        sizer_38.Add(bitmap_5, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_37.Add(sizer_38, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.panel_19, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.panel_18, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.panel_21, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.panel_20, 0, wx.EXPAND, 0)
        bitmap_3 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("logos/image_example copy.jpg", wx.BITMAP_TYPE_ANY), style=wx.BORDER_SUNKEN | wx.FULL_REPAINT_ON_RESIZE)
        grid_sizer_3.Add(bitmap_3, 0, wx.ALIGN_CENTER, 5)
        grid_sizer_3.Add(self.panel_22, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.panel_23, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.panel_24, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.panel_25, 0, wx.EXPAND, 0)
        sizer_37.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        sizer_36.Add(sizer_37, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_36)
        self.Layout()
        # end wxGlade

# end of class MyFrame5

class MyApp(wx.App):
    def OnInit(self):
        self.Controls = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.Controls)
        self.Controls.Show()

        self.One = MyFrame1(None, wx.ID_ANY, "")
        self.Two = MyFrame2(None, wx.ID_ANY, "")
        self.Three = MyFrame3(None, wx.ID_ANY, "")
        self.Four = MyFrame4(None, wx.ID_ANY, "")
        self.Five = MyFrame5(None, wx.ID_ANY, "")

        self.One.Show()
        self.Two.Show()
        self.Three.Show()
        self.Four.Show()
        self.Five.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    Cockpit_1 = MyApp(0)
    Cockpit_1.MainLoop()
